
PARETO_COMPLEXITY_KEY = "pareto_complexity"
PARETO_LOSS_KEY = "pareto_loss"
PARETO_NMSE_KEY = "pareto_nmse"
PARETO_EXPRESSIONS_KEY = "pareto_expressions"
PARETO_SCALE_KEY = "pareto_scale"
SELECTED_COMPLEXITY_KEY = "selected_complexity"
SELECTED_LOSS_KEY = "selected_loss"
SELECTED_NMSE_KEY = "selected_nmse"






SEARCH_TOPK_EXPRESSIONS_KEY = "search_topk_expressions"
SEARCH_TOPK_SCORES_KEY = "search_topk_scores"
SEARCH_TOPK_TERMS_KEY = "search_topk_terms"
SEARCH_TOPK_LHS_KEY = "search_topk_lhs"
SEARCH_TRAJECTORY_KEYS = (
    SEARCH_TOPK_EXPRESSIONS_KEY,
    SEARCH_TOPK_SCORES_KEY,
    SEARCH_TOPK_TERMS_KEY,
    SEARCH_TOPK_LHS_KEY,
)

__all__ = [
    "PARETO_COMPLEXITY_KEY",
    "PARETO_EXPRESSIONS_KEY",
    "PARETO_LOSS_KEY",
    "PARETO_NMSE_KEY",
    "PARETO_SCALE_KEY",
    "SELECTED_COMPLEXITY_KEY",
    "SELECTED_LOSS_KEY",
    "SELECTED_NMSE_KEY",
    "SEARCH_TOPK_EXPRESSIONS_KEY",
    "SEARCH_TOPK_SCORES_KEY",
    "SEARCH_TOPK_TERMS_KEY",
    "SEARCH_TOPK_LHS_KEY",
    "SEARCH_TRAJECTORY_KEYS",
]
